// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type File struct {
	Ownerid   string     `json:"ownerid"`
	Objkey    string     `json:"objkey"`
	Filename  string     `json:"filename"`
	ID        string     `json:"id"`
	Size      int64      `json:"size"`
	Expiresat *time.Time `json:"expiresat"`
}

type User struct {
	Username string `json:"username"`
	Space    int64  `json:"space"`
}
